<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>$PROJECT_NAME$</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="EppoScriptCore.Managed">
      <HintPath>$APP_DIR$/EppoScriptCore.Managed.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
