<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Test</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="EppoScriptCore.Managed">
      <HintPath>..\..\..\..\build\debug\EppoEditor\Debug\EppoScriptCore.Managed.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
