name: CI

on:
  workflow_dispatch:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  config-matrix:
    runs-on: [ self-hosted ]
    name: "Build and Test"
    strategy:
      matrix:
        config: [ linux-debug, linux-release, linux-dist ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run CMake Configure
        run: cmake --preset=${{ matrix.config }}

      - name: Run CMake Build
        run: cmake --build --preset=${{ matrix.config }}